@startuml
skinparam linetype polyline

class Server {
   name : String
   ip : String
}



class Event {
   time : LocalDateTime
   duration : Integer
   threadId : String
   userId : String
   description : String
   analysisRequired : Boolean
}

class ExceptionEvent {
   exceptionName : String
   occuranceClass : String
   occuranceMethod : String
   occuranceLine : Integer
}

class RequestEvent {
   method : HttpMethod
}

class SqlEvent {
   sqlQuery : String
}



Event "0..*" - "1..*" Server : occured on >

Event <|-- RequestEvent
Event <|-- SqlEvent
Event <|-- ExceptionEvent


@enduml
