version: 2
jobs:
        build:
          docker:
            - image: texlive/texlive-full:2017

          working_directory: ~/repo

          environment:
            TERM: dumb

          steps:
            - checkout
            - attach_workspace:
                at: ./artifacts
            - run: ./build.sh
            - persist-to-workspace:
                root: .
                paths:
                    - out

        publish:
          docker:
            - image: cibuilds/github:0.10
          steps:
            - attach_workspace:
                at: ./artifacts
            - run:
                name: "Publish documents on GitHub"
                command: |
                    ls ./artifacts/out
                    ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -replace ${CIRCLE_TAG} ./artifacts/out
            
workflows:
    version: 2
    build-and-deploy:
        jobs:
            - build:
                filters:
                    branches:
                        only:
                            - master
                            - develop
                    tags:
                        only:
                            - /^\d\d\d\d\.\d\d\.\d\d$/
            - publish:
                filters:
                    branches:
                        ignore:
                            - master
                            - develop
                    tags:
                        only:
                            - /^\d\d\d\d\.\d\d\.\d\d$/
                requires: 
                    - build
                    
