version: 2
jobs:
        build-tex:
          docker:
            - image: flowfx/circleci-python-texlive:0.0.6
          working_directory: ~/repo
          environment:
            TERM: dumb
          steps:
            - checkout
            - attach_workspace:
                at: ./artifacts
            - run: ./build.sh
            - persist-to-workspace:
                root: .
                paths:
                    - out

        build-adoc:
          docker:
            - image: circleci/ruby:3.0.0
          working_directory: ~/repo
          steps:
            - checkout
            - run: bundle install
            - run: bash ./build-adoc.sh
            - deploy:
                name: Deploy Release to GitHub
                command: |
                  if [ $CIRCLE_BRANCH == 'master' ]; then
                    bash .circleci/setup-github.sh
                  fi

        publish:
          docker:
            - image: cibuilds/github:0.10
          steps:
            - attach_workspace:
                at: ./artifacts
            - run:
                name: "Publish documents on GitHub"
                command: |
                    ls ./artifacts/out
                    ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -replace ${CIRCLE_TAG} ./artifacts/out
            
workflows:
    version: 2
    build-and-deploy:
        jobs:
            - build-adoc:
                filters:
                  branches:
                    only:
                      - master
            - build-tex:
                filters:
                    branches:
                        only:
                            - master
                            - develop
                    tags:
                        only:
                            - /^\d\d\d\d\.\d\d\.\d\d$/
            - publish:
                filters:
                    branches:
                        ignore:
                            - master
                            - develop
                    tags:
                        only:
                            - /^\d\d\d\d\.\d\d\.\d\d$/
                requires: 
                    - build-tex
