= Projekt i implementacja systemów webowych
:release-tag: 2021.02.15
:toc: left
:toc-title: Spis treści
:table-caption: Tabela

Strona z materiałami dydaktycznymi dotyczącymi wykładu oraz zajęć laboratoryjnych.

== Wykład

=== Komunikacja

Publiczny kanał Gitter dla grupy wykładowej 2020/2021 (prosimy o dołączenie):
image:https://badges.gitter.im/pwr-piisw/wyklad2021.svg[link=https://gitter.im/pwr-piisw/wyklad2021?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge]

=== Harmonogram

include::_wyklad-harmonogram.adoc[]

=== Konsultacje

mgr inż. Szymon Jaśniak:: tbd
mgr inż. Maciej Małecki:: *Wtorek 14:00-15:00*. Proszę o wcześniejszy kontakt mailowy (maciej.malecki _@_ pwr.edu.pl) lub o bezpośredni kontakt poprzez aplikację https://gitter.im (chat).
mgr inż. Marcin Nowak:: tbd

=== Bibliografia

include::_wyklad-bibliografia.adoc[leveloffset=+2]

== Laboratorium

xref:laboratorium.adoc[Zasady zaliczenia zajęć]

=== Listy zadań

[horizontal]
https://github.com/pwr-piisw/materialy/releases/download/{release-tag}/lista_0.pdf[Lista 0]:: 2021-03-01
Lista 1:: 2021-03-08 (zaliczenie do 2021-03-14)
Lista 2:: 2021-03-15 (zaliczenie do 2021-03-21)
Lista 3:: 2021-03-22 (zaliczenie do 2021-03-28)
Lista 4:: 2021-03-29 (zaliczenie do 2021-04-11)
Lista 5:: 2021-04-12 (zaliczenie do 2021-04-18)
//https://github.com/pwr-piisw/materialy/releases/download/{release-tag}/lista_1.pdf[Lista 1]:: 2021-03-08 (zaliczenie do 2021-03-15)
//https://github.com/pwr-piisw/materialy/releases/download/{release-tag}/lista_2.pdf[Lista 2]:: 2021-03-15 (zaliczenie do 2021-03-22)
//https://github.com/pwr-piisw/materialy/releases/download/{release-tag}/lista_3.pdf[Lista 3]:: 2021-03-22 (zaliczenie do 2021-03-29)
//https://github.com/pwr-piisw/materialy/releases/download/{release-tag}/lista_4.pdf[Lista 4]:: 2021-03-29 (zaliczenie do 2021-04-12)
//https://github.com/pwr-piisw/materialy/releases/download/{release-tag}/lista_5.pdf[Lista 5]:: 2021-04-12 (zaliczenie do 2021-04-19)

=== Bibliografia

include::_lab-bibliografia.adoc[leveloffset=+2]