= Projekt i implementacja systemów webowych
:release-tag: 2021.03.21
:toc: left
:toc-title: Spis treści
:table-caption: Tabela
:icons: font

Strona z materiałami dydaktycznymi dotyczącymi wykładu oraz zajęć laboratoryjnych.

*Semestr letni 2020/2021*

== Konsultacje

include::_konsultacje.adoc[]

== Wykład

=== Komunikacja

Publiczny kanał Gitter dla grupy wykładowej 2020/2021 (prosimy o dołączenie):
image:https://badges.gitter.im/pwr-piisw/wyklad2021.svg[link=http://gitter.im/pwr-piisw/wyklad2021?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge]

Wykłady będą prowadzone z wykorzystaniem platformy Zoom. Zaproszenia na wykłady będą wysyłane z ok. tygodniowym wyprzedzeniem.

Strona kursu na platformie ePortal: https://eportal.pwr.edu.pl/course/view.php?id=27584 (rozwiązanie zapasowe).

=== Harmonogram

Wykłady odbywają się w poniedziałki o godzinie 7:30.

TIP: Linki do slajdów będą pojawiać się najpóźniej w dniu wykładu.

include::_wyklad-harmonogram.adoc[]

=== Bibliografia

include::_wyklad-bibliografia.adoc[leveloffset=+2]

== Laboratorium

xref:laboratorium.adoc[Zasady zaliczenia zajęć]

=== Grupy laboratoryjne

[cols="1,1,1"]
|===
|Godzina|Prowadzący|Informacje

|Poniedziałek, 9:15-11:00
|Maciej Małecki
|image:http://badges.gitter.im/pwr-piisw/lab2021-mmalecki.svg[link=https://gitter.im/pwr-piisw/lab2021-mmalecki?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge] - chat dla całej grupy

|Poniedziałek, 9:15-11:00
|Marcin Nowak
|image:http://badges.gitter.im/pwr-piisw/lab2021mnowak.svg[link=https://gitter.im/pwr-piisw/lab2021mnowak?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge] - chat dla całej grupy

|Poniedziałek, 11:15-13:00
|Szymon Jaśniak
|image:http://badges.gitter.im/pwr-piisw/lab2021sjasniak.svg[link=https://gitter.im/pwr-piisw/lab2021sjasniak?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge] - chat dla całej grupy

|===

=== Listy zadań

[horizontal]
https://github.com/pwr-piisw/materialy/releases/download/2021.02.26/lista_0.pdf[Lista 0]:: 2021-03-01
https://github.com/pwr-piisw/materialy/releases/download/2021.03.04/lista_1.pdf[Lista 1]:: 2021-03-08 (zaliczenie do 2021-03-14)
https://github.com/pwr-piisw/materialy/releases/download/2021.02.26/lista_2.pdf[Lista 2]:: 2021-03-15 (zaliczenie do 2021-03-21)
https://github.com/pwr-piisw/materialy/releases/download/2021.03.14/lista_3.pdf[Lista 3]:: 2021-03-22 (zaliczenie do 2021-03-28)
https://github.com/pwr-piisw/materialy/releases/download/2021.03.15/lista_4.pdf[Lista 4]:: 2021-03-29 (zaliczenie do 2021-04-11)
https://github.com/pwr-piisw/materialy/releases/download/2021.03.21/lista_5.pdf[Lista 5]:: 2021-04-12 (zaliczenie do 2021-04-18)


=== Bibliografia

include::_lab-bibliografia.adoc[leveloffset=+2]
