= Projekt i implementacja systemów webowych
:release-tag: 2022.03.21
:toc: left
:toc-title: Spis treści
:table-caption: Tabela
:icons: font

Strona z materiałami dydaktycznymi dotyczącymi wykładu oraz zajęć laboratoryjnych.

*Semestr letni 2022/2023*

== Konsultacje

t.b.d.

// include::_konsultacje.adoc[]

== Wykład

=== Komunikacja

Publiczny kanał Gitter dla grupy wykładowej 2021/2022 (prosimy o dołączenie):
image:https://badges.gitter.im/pwr-piisw/wyklad2022.svg[link=http://gitter.im/pwr-piisw/wyklad2022?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge]

Wykłady będą prowadzone z wykorzystaniem platformy Zoom. Zaproszenia na wykłady będą wysyłane z ok. tygodniowym wyprzedzeniem.

=== Harmonogram

Wykłady odbywają się w czwartki o godzinie 13:15.

TIP: Linki do slajdów będą pojawiać się najpóźniej w dniu wykładu.

include::_wyklad-harmonogram.adoc[]

=== Bibliografia

include::_wyklad-bibliografia.adoc[leveloffset=+2]

== Laboratorium

xref:laboratorium.adoc[Zasady zaliczenia zajęć]

=== Grupy laboratoryjne

[cols="1,1,1"]
|===
|Godzina|Prowadzący|Informacje

|Czwartek, 15:15-16:55
|Maciej Małecki
|

|Czwartek, 17:05-18:50
|Kamil Kompała
|

|Czwartek, 18:55-20:35
|Dominika Janus
|

|===

=== Listy zadań

[horizontal]
https://github.com/pwr-piisw/materialy/releases/download/2022.03.06/lista_1.pdf[Lista 1]:: HTML i CSS
https://github.com/pwr-piisw/materialy/releases/download/2022.03.06/lista_2.pdf[Lista 2]:: JavaScript
https://github.com/pwr-piisw/materialy/releases/download/2022.03.21/lista_3.pdf[Lista 3]:: Backend/Springboot
https://github.com/pwr-piisw/materialy/releases/download/2022.03.27/lista_4.pdf[Lista 4]:: JPA
https://github.com/pwr-piisw/materialy/releases/download/2022.04.01/lista_5.pdf[Lista 5]:: Angular

=== Harmonogram zajęć
include::_lab-harmonogram.adoc[]

=== Bibliografia

include::_lab-bibliografia.adoc[leveloffset=+2]
