= Projekt i implementacja systemów webowych
Maciej Małecki <maciej.malecki@pwr.edu.pl>
:icons: font

Poniedziałek, 9:15

xref:index.adoc[Powrót do strony głównej]

== Części projektowa

[IMPORTANT]
.Ocena końcowa
====
Kompletna realizacja niżej wymienionych punktów będzie skutkowała oceną bardzo dobrą dla wszystkich członków zespołu. Szerszy zakres projektu może skutkować podwyższeniem oceny.
====

=== Zgłaszanie grup i tematów projektowych
* Studenci powinni podzielić się w 3-4 osobowe grupy, realizujące projekt wspólnie.
* Najpóźniej w dniu 2021-04-19 jeden z członków grupy powinien zgłosić prowadzącemu (na Gitterze) listę członków/członkiń zespołu, nazwę kodową zespołu oraz temat projektu i opis projektu.
* Opis projektu powinien zawierać nazwę, cel, stos technologiczny aplikacji oraz zakres, który będzie zrealizowany i zaprezentowany na każdym z trzech spotkań: 2021-05-17, 2021-05-31, 2021-06-14.

=== Założenia wstępne

W ramach zajęć laboratoryjny grupa studentów/studentek realizuje wspólnie projekt o dowolnej tematyce, który musi składać się z następujących elementów technicznych:

. Klient webowy zrealizowany w architekturze SPA (Single Page App).
. Część _backendowa_/serwerowa pełniąca następujące funkcje:
.. serwowanie klienta SPA,
.. realizacja funkcji serwerowej,
.. wystawienie intefejsu (np. _RESTful_) dla klienta SPA.
. Integracja klienta SPA oraz części serwerowej z wykorzystaniem wybranego protokołu (np. _RESTful_).
. Mechanizm składowania oparty o dowolną bazę danych (SQLową lub No-SQL).
. Integracja części serwerowej z wybraną bazą danych.

=== Zakres/rozmiar projektu

Klient webowy powinien składać się przynajmniej z dwóch kompletnych ekranów skojarzonych z dwoma ścieżkami URL (_routes_).
Każdy z tych dwóch ekranów powinien być widokiem złożonym, tj zawierać elementy takie jak np. lista z funkcją sortowania i filtrowania i/lub formularz z walidacją danych wejściowych.

Część backendowa oraz bazodanowa powinna realizować wszystkie funkcjonalności niezbędne do realizacji wyżej wymienionych ekranów.

=== Wymagania niefunkcjonalne

. Przynajmniej jeden z ekranów powinien być kompletnie przetestowany przy użyciu testów jednostkowych (frontendowych).
. Funkcjonalność serwerowa odpowiadająca także jednemu z ekranów także powinna być przetestowana przy użyciu testów jednostkowych (np. JUnit dla Javy). Należy pamiętać o odpowiednim mockowaniem (np z wykorzystaniem biblioteki Mockito).
. Projekt powinien budować się automatycznie (zarówno frontend jak i backend) włącznie z wykonywaniem wszystkich napisanych testów na środowisku CircleCI.
. Źródła projektu powinny być umieszczone w repozytorium na portalu GitHub (dopuszczalne jest użycie repozytorium publicznego). Prowadzący powinien mieć dostęp do tego repozytorium.
. Do projektu należy dołączyć szczegółową instrukcję (w postaci pliku README) opisującego sposób budowania i uruchamiania aplikacji.

