= Projekt i implementacja systemów webowych
mgr inż. Maciej Małecki <maciej.malecki@pwr.edu.pl>
:icons: font
:table-caption: Tabela
:toc: left
:toc-title: Spis treści

== Organizacja zajęć

Zajęcia laboratoryjne są prowadzone bez przerwy przez 1,5 godziny.

== Konsultacje

include::_konsultacje.adoc[]

== Ocena

* Skala ocen na zaliczenie: 5{nbsp}(bdb), 4,5{nbsp}(+db), 4{nbsp}(db), 3,5{nbsp}(+dst), 3{nbsp}(dst), 2{nbsp}(ndst).
* Zaliczenie na ocenę 5,5{nbsp}(cel) może uzyskać student, który wykaże się wiedzą lub umiejętnościami znacznie wykraczającymi poza zakres przewidziany w programie nauczania.
* Indywidualnej ocenie podlega 5 list zadań (realizowanych na zajęciach 2--6) oraz 3 etapy projektowe realizowane podczas drugiej częsci semestru.
* Na każdej z list zadań określona jest skala punktowa, na podstawie której wystawiana jest ocena.
* Ocena końcowa jest średnią ważoną ocen cząstkowych. Oceny za listy zadań mają wagę{nbsp}1, oceny za etapy projektu mają wagę{nbsp}2.

== Wymagania

* Na zajęcia należy przychodzić punktualnie.
* Uczestnictwo w zajęciach laboratoryjnych jest obowiązkowe: dopuszcza się jedną nieobecność nieusprawiedliwioną i jedną nieobecność usprawiedliwioną w semestrze.
* Materiał z zajęć, na których student nie był obecny, musi być opanowany a zadania wykonane.
* Na zajęcia należy przygotować się poprzez zapoznanie się z materiałem z wykładów i z wcześniej zapowiedzianymi tematami zajęć.
* Uwagi ogólne dotyczące zaliczeń:
** W tabeli <<_harmonogram_zajęć_laboratoryjnych>> określono termin zaliczeń dla każdej z list zadań oraz każdego etapu projektu.
//** Zadań lub etapów projektu nie można oddawać na konsultacjach.
** Zadania lub etap projektu oddane na następnych zajęciach po obowiązującym terminie są oceniane najwyżej na ocenę dostateczną (3), materiał oddany po tym czasie oceniany jest na ocenę 2{nbsp}(ndst).
* Szczegółowe zasady dotyczące prac z listami zadań:
** Na pierwszych pięciu zajęciach studenci rozwiązują *osobiście* listy zadań.
** Lista zadań nr{nbsp}0 realizowana na pierwszych zajęciach nie podlega ocenie.
** Listy zadań dostepne są pod następującym adresem: https://pwr-piisw.github.io/materialy/.
** Na każdej liście zadań umieszczone są informacje, w jaki sposób rozwiązania zadań należy umieszczać w repozytorium GitHub.
* Szczegółowe zasady dotyczące pracy z kodem podczas fazy projektowej:
** Na zajęciach 7-mych studenci tworzą 3--4 osobowe grupy projektowe, w ramach których realizować będą projekt.
** Każda grupa projektowa powinna zgłosić prowadzącemu temat projektu na 7-mych zajęciach. Temat może być zgłoszony z listy umieszczonej na końcu tego dokumentu, może być to także własny projekt pod warunkiem przedstawienia adekwatnego opisu.
** Każdy zespół projektowy zobowiązany jest do utworzenia prywatnego repozytorium projektowego na portalu GitHub. Prowadzącemu zajęcia należy nadać prawa zapisu i odczytu do tego repozytorium.
** Wszyscy członkowie zespołu zobowiązani są do wprowadzania zmian bezpośrednio do prywatnego repozytorium zespołu.
** Każdy członek zespołu zobowiązany jest utrzymywać repozytorium w stanie “zielonym” - CI po zmianach powinno być zielone, w przypadku wystąpienia błędów należy je niezwłocznie usuwać.
** Podczas oddawania danego etapu zadania prowadzący sprawdza stan CI - niestabilne CI może być przyczyną niezaliczenia etapu.
** Zmiany w repozytorium (kodzie aplikacji) powinny być odpowiednio i czytelnie komentowane (ang. `commit message`).
** W przypadku każdego z trzech etapów zaliczeniowych należy utworzyć w repozytorium _tag_ o nazwach odpowiednio: `etap1`, `etap2` oraz `etap3`.
** Zaimplementowany system powinien dać się uruchomić na dowolnym komputerze wyposażonym w system Microsoft Windows.

Wpływ na ocenę będzie miało:

* Spełnienie wymagań funkcjonalnych i niefunkcjonalnych.
* Jakość rozwiązania – zarówno wewnętrzna jak i zewnętrzne.
* Strategia testowania i zastosowane narzędzia.
* Zastosowane narzędzia deweloperskie.

WARNING: Kopiowanie prac innych studentów skutkuje automatycznie niezaliczeniem zajęć!

== Harmonogram zajęć laboratoryjnych

include::_lab-harmonogram.adoc[]

== Propozycje tematów projektów

Istnieje możliwość  propozycji własnych tematów projektów związanych z przedmiotem "Projekt i implementacja systemów webowych". Informację należy podać na 7-mych zajęciach (2021-04-19) i uzyskać akceptację prowadzącego.

Zakres każdego z projektów powinien obejmować realizację dwóch ekranów aplikacji webowej, interfejsu REST łączącego frontend i backend, dodatkowego interfejsu REST przeznaczonego do integracji z zewnętrznym systemem oraz warstwę utrwalania danych zrealizowaną np w oparciu o relacyjną bazę danych oraz mapowanie JPA.

Dashboard systemu inteligentnego domu:: Aplikacja prezentuje odczyty domowych mierników. Wartości odczytów przesyłane są do aplikacji za pośrednictwem interfejsu REST.
System sprzedaży biletów kinowych:: Aplikacja umożliwia rezerwację biletów na seans kinowy. System wystawia zewnętrzny interfejs REST umożliwiający elektroniczną weryfikację biletu.
Tablica ogłoszeń drobnych:: System umożliwia publikację ogłoszeń wraz z informacjami kontaktowymi. System publikuje interfejs REST pozwalający na przeszukiwanie ogłoszeń przez zewnętrzny system agregujący lub indeksujący. Nie ma konieczności integracji z żadnym systemem agregującym, interfejs może być dowolny.
Elektroniczny bilet miejski:: Użytkownik uzyskuje możliwość rejestracji w serwisie oraz wygenerowanie wirtualnego biletu umożliwiającego korzystanie z systemu transportu zbiorowego. System wystawia zewnętrzny interfejs pozwalający na walidację biletów przez kontrolera. Dla uproszczenia można przyjąć identyfikację z wykorzystaniem unikalnego identyfikatora UUID.
