= Projekty do wyboru

== System sprzedaży biletów kinowych
Aplikacja umożliwia rezerwację biletów na seans kinowy oraz weryfikację ważności biletów.

Użytkownik (widz), bez konieczności logowania się do systemu może przeglądać dostępny repertuar (data, godzina i czas trwania seansów; film, jego opis oraz zdjęcie).

Widz może kupić bilety na wybrany seans o ile są wolne miejsca.
Kupno biletów wymaga wybór seansu (data, godzina oraz sala - kino może składać się z wielu sal) oraz rezerwacji miejsc.
Klient dokonuje wyboru miejsca na widoku reprezentującym schematyczną salę kinową z zaznaczonym ekranem oraz rzędami foteli.
Klient zaznacza kliknięciem interesującą go liczbę foteli oraz potwierdza rezerwację.
W efekcie wygenerowany zostaje unikalny kod rezerwacji, który jest dowodem zakupu biletu.

WARNING: Repertuar kinowy, sale oraz katalog filmów można/należy "zahardkodować w systemie".

Bileter jest uprawnionym użytkownikiem, który posiada możliwość sprawdzenia ważności biletu dla wprowadzonego kodu.
Bilet może w jednym z następujących stanów: nie istnieje, ważny, skasowany, nieważny.

Bilet jest ważny jedynie w czasie poprzedzającym 15 minut seans, traci zaś ważność z końcem seansu.

Bileter oprócz stanu biletu, powinien także zobaczyć ilość zarezerwowanych miejsc, nr sali oraz numery miejsc.
Bileter powinien mieć możliwość skasowania biletu, a więc zmianę jego stanu z ważny do skasowany.

System powinien obsługiwać dwie klasy użytkowników:

Widzowie:: Przeglądanie repertuaru oraz kupno biletu na wskazany seans oraz rezerwacja wybranych miejsc na sali kinowej.
Bileterzy:: Funkcja sprawdzenia ważności oraz skasowania biletu. Dostęp do funkcjonalności wymaga wcześniejszego zalogowania się do systemu.

== Tablica ogłoszeń drobnych
System umożliwia publikację ogłoszeń wraz z informacjami kontaktowymi.

Sprzedający posiadają w systemie odpowiednie konta.
Po zalogowaniu mają oni możliwość dodawania, edytowania i usuwania własnych ogłoszeń drobnych.

Ogłoszenie składa się z tytułu, opisu, galerii zdjęć oraz tagów.

Sprzedający posiada pewną ilość danych kontaktowych (telefon, email), które może udostępniać wraz z ogłoszeniem.
Dla każdego ogłoszenia można dane kontaktowe udostępniać indywidualnie.

Dostępna jest też poczta wewnętrzna, która pozwala na komunikację ze sprzedającym bez użycia zewnętrznego adresu email i telefonu.
Poczta wewnętrzna jest zawsze dostępna (może być jedynym środkiem komunikacji).

Sprzedający mogą swobodnie dodawać własne tagi lub podpinać się do tagów już istniejących.

Ogłoszenie może być w trzech stanach: wersja robocza, opublikowane, archiwum.
Ogłoszenie w stanach: wersja robocza i archiwum jest widoczne jedynie dla ogłoszeniodawcy.

Ogłoszeniodawca powinien mieć możliwość poglądu wersji roboczej aby zobaczyć, jak ogłoszenie będzie finalnie wyglądać.
Tę funkcjonalność można zrealizować np z użyciem losowo wygenerowanego tajnego linku.

Kupujący mogą przeszukiwać bazę opublikowanych ogłoszeń z wykorzystaniem wyszukiwania tekstowego (po nazwie i opisie) oraz po tagach.

System powinien w wyszukiwarce podpowiadać tagi sortując je wg częstości użycia, na podstawie wprowadzonych znaków.

System powinien udostepniać prosty mechanizm poczty wewnętrznej.
Poczta powinna umożliwiać wysłanie wiadomości tekstowej od jednego do drugiego użytkownika systemu.
Poczta powinna zawierać zakładkę z zawartością skrzynki z wiadomościami.
Powinna być dostępna funkcja: odpowiedz.

System powinien obsługiwać dwie klasy użytkowników:

Kupujący:: Funkcja nie wymaga zalogowania się do systemu. Kupujący może przeglądać ogłoszenia. Kupujący, po zalogowaniu, otrzymuje dodatkowo możliwość korzystania z poczty wewnętrznej.
Ogłoszeniodawcy:: Funkcja wymaga zalogowania się do systemu z użyciem loginu i hasła.

== Elektroniczny bilet miejski
Użytkownik uzyskuje możliwość rejestracji w serwisie oraz wygenerowanie wirtualnego biletu umożliwiającego korzystanie z systemu transportu zbiorowego.
System umożliwia weryfikację sprawdzanych biletów.

Pasażer może założyć sobie konto w systemie.
W ramach konta możliwe jest przeglądanie dostępnej oferty biletowe (bilety czasowe, jednorazowe, okresowe; ulgowe i normalne).
Pasażer może wybrać dowolny bilet, wybrać jego ważność (w przypadku biletów czasowych i okresowych) oraz dokonać zakupu.
Po zakupie, bilet pojawia się w zakładce "moje bilety".
Każdy bilet posiada unikalnie wygenerowany kod, umożliwiający jego walidację.

System powinien posiadać prosty interfejs REST pozwalający na zintegrowanie z systemem kasowników (każdy bilet jednorazowy i czasowy wymaga skasowania, bilet nieskasowany jest nieważny).

Bileter posiada możliwość sprawdzenia ważności biletu - w tym celu konieczne jest wprowadzenie kodu biletu oraz identyfikatora pojazu.
Bilet może być ważny lub nieważny.
Bilet jest ważny tylko wtedy, gdy:

* W przypadku biletu okresowego - data kontroli zawiera się w okresie ważności biletu.
* W przypadku biletu jednorazowego - bilet został skasowany w pojeździe, w którym przeprowadzana jest kontrola.
* W przypadku biletu czasowego - nie upłynął czas ważności biletu od momentu skasowania biletu.

System powinien obsługiwać dwie klasy użytkowników:

Pasażer:: Funkcja wymaga zalogowania się do systemu. Kupujący może przeglądać dostępną ofertę biletową, kupić bilet oraz podglądać zakupione bilety wraz z historią transakcji.
Bileter:: Funkcja wymaga zalogowania się do systemu. Bileter może sprawdzać ważność kodu biletu.
